// Generated by CoffeeScript 1.7.1
(function() {
  var AsyncUglifyJsPlugin, UglifyJS, compileAsync, crypto, fs, isStale, log, md5, minimizeTask, options, path, timers,
    __slice = [].slice;

  crypto = require('crypto');

  fs = require('fs');

  path = require('path');

  UglifyJS = require('uglify-js');

  timers = {};

  options = {
    delay: 5000,
    minifyOptions: {},
    logger: false,
    done: function(path, originalContents) {
      return log("minimized " + path);
    }
  };

  log = function() {
    var msg;
    msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (options.logger) {
      return console.log.apply(console, msg);
    }
  };

  md5 = function(buffer) {
    var content, hash;
    content = buffer.toString();
    hash = crypto.createHash('md5');
    hash.update(content);
    return hash.digest('hex');
  };

  isStale = function(chunk) {
    var hash, stale;
    hash = md5(fs.readFileSync(chunk.path));
    stale = hash !== chunk.fullhash;
    if (stale) {
      log("minification cancelled (file has changed!) " + chunk.path);
    }
    return stale;
  };

  minimizeTask = function(chunk) {
    return function() {
      return fs.readFile(chunk.path, function(err, buffer) {
        if (err) {
          throw err;
        }
        if (isStale(chunk)) {
          return;
        }
        log("starting minification " + chunk.path);
        return fs.writeFile(chunk.path, buffer, function(err) {
          var contents, result;
          if (err) {
            throw err;
          }
          contents = buffer.toString();
          result = UglifyJS.minify(contents, options.minifyOptions);
          if (isStale(chunk)) {
            return;
          }
          return options.done(chunk.path, contents);
        });
      });
    };
  };

  compileAsync = function(chunk, delay) {
    clearTimeout(timers[chunk.id]);
    chunk.path = path.resolve('builds', chunk.files[0]);
    return fs.readFile(chunk.path, function(err, buffer) {
      chunk.fullhash = md5(buffer);
      return timers[chunk.id] = setTimeout(minimizeTask(chunk), options.delay);
    });
  };

  AsyncUglifyJsPlugin = (function() {
    function AsyncUglifyJsPlugin(_options) {
      var option, value;
      if (_options == null) {
        _options = {};
      }
      for (option in _options) {
        value = _options[option];
        options[option] = value;
      }
      options.minifyOptions.fromString = true;
    }

    AsyncUglifyJsPlugin.prototype.apply = function(compiler) {
      return compiler.plugin('done', function(stats) {
        var chunk, _i, _len, _ref, _results;
        stats = stats.toJson();
        _ref = stats.chunks;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          chunk = _ref[_i];
          _results.push(compileAsync(chunk));
        }
        return _results;
      });
    };

    return AsyncUglifyJsPlugin;

  })();

  module.exports = AsyncUglifyJsPlugin;

}).call(this);
